### ISSUE TITLE
Waybar remove

### ISSUE THREAD

**Issue by aacle** [JaKooLit/Hyprland-v2#1]
is There any way to remove waybar from secondary monitor only because whenever i do full screen in my secondary monitor it the monitor starts screen off

**Comment by JaKooLit** [comment]
In theory yes (I have not tried so dont quote me)

[{
    "layer": "top",
    "output": "eDP-1",
    "modules-left": ["sway/workspaces", "sway/mode"],
    //...
}, {
    "layer": "top",
    "output": "VGA",
    "modules-right": ["clock"],
    //...
}]

https://github.com/Alexays/Waybar/wiki/Configuration
