### ISSUE TITLE
LAN(eth) Connection Failed Between 2 PCs

### ISSUE THREAD

**Issue by aacle** [JaKooLit/Hyprland-v2#2]
I'm not able to connect my another pc threw LAN (eth) with my main pc

Can you try if this same issue comes with you too ?

**Comment by JaKooLit** [comment]
can you check network manager status?

systemctl status NetworkManager

if not running try restart

sudo systemctl restart NetworkManager.service

enable at boot

sudo systemctl enable --now NetworkManager.service

if not, click on the networkmanager applet.

click enable networking something....

**Comment by aacle** [comment]
Its running fine bro & I'm am able use my internet threw wlan0 interface but I am not able to connect my other pc threw eth0 interface threw LAN

**Comment by JaKooLit** [comment]
im closing this. This has something to do with internet sharing lan sharing which should be covered by Arch wiki
